version: "3.8"

services:
  react-app:
    container_name: sonoraq-con
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Syncs your local files with the container
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables hot reloading for file changes
    stdin_open: true
    tty: true
